export const DEFAULT_HOMEPAGE_CONTENT = {
    heroTitle: "Medical Weight Loss That Works",
    heroDescription:
        "Weight Loss MD provides comprehensive medical weight management programs designed by physicians to help you achieve sustainable, healthy weight loss.",
    heroButtonText: "Get Started",
    heroButtonLink: "/contact",
    heroButtonNewTab: false,

    assessmentTitle: "Start Your Weight Loss Journey Today",
    assessmentDescription:
        "Physician-supervised programs tailored to your unique needs. Get personalized care from board-certified weight loss specialists.",

    aboutTitle: "Colorado's Premier Medical Weight Loss Clinic",
    aboutDescription:
        "Weight Loss MD has been helping patients across Colorado achieve their weight loss goals through evidence-based medical treatments and personalized care plans. Our board-certified physicians provide comprehensive support every step of the way.",
    aboutButtonText: "Learn More",
    aboutButtonLink: "/about",
    aboutButtonNewTab: false,

    providersTitle: "Meet our expert providers",
    providersButtonText: "Book an Consultation",
    providersButtonLink: "https://weightlossmd.com/contact",
    providersButtonNewTab: true,

    howItWorksTitle: "How It Works",
    howItWorksStep1Title: "Complete Your Medical Intake",
    howItWorksStep1Description: "Share your health history and goals",
    howItWorksStep2Title: "Provider Evaluation",
    howItWorksStep2Description: "A licensed medical provider reviews your information",
    howItWorksStep3Title: "Personalized Treatment Plan",
    howItWorksStep3Description: "Based on your individual needs and clinical assessment",
    howItWorksStep4Title: "Ongoing Support & Monitoring",
    howItWorksStep4Description: "Adjustments made as appropriate over time",

    testimonialTitle: "Patient Success Stories",
    testimonialCardTitle: "Read from Hundreds of success stories",
    testimonialCardDescription: "See how Weight Loss MD has helped people feel stronger, healthier, and more balanced.",
    testimonialButtonText: "Book intake session",
    testimonialButtonLink: "https://weightlossmd.com/contact",
    testimonialButtonNewTab: true,

    faqTitle: "Frequently asked questions",
    faqCardTitle: "Still have a Question?",
    faqCardDescription: "Everything you need to know before getting started.",
    faqButtonText: "Book intake session",
    faqButtonLink: "https://weightlossmd.com/contact",
    faqButtonNewTab: true,
    faqQuestion1: "What weight loss treatments do you offer?",
    faqAnswer1: "We offer medically supervised weight loss programs that may include GLP-1 medications such as semaglutide and tirzepatide, appetite suppressants, B12 injections, lipotropic injections, nutritional guidance, and personalized wellness support. Treatment plans are customized based on your health goals and medical history.",
    faqQuestion2: "How do GLP-1 medications help with weight loss?",
    faqAnswer2: "GLP-1 medications mimic a natural hormone that targets areas of the brain that regulate appetite and food intake, helping you feel fuller longer.",
    faqQuestion3: "What is the difference between semaglutide and tirzepatide?",
    faqAnswer3: "Semaglutide is a single receptor agonist (GLP-1), while tirzepatide is a dual receptor agonist (GLP-1 and GIP), which may offer enhanced weight loss efficacy.",
    faqQuestion4: "Do I need a prescription for weight loss medications?",
    faqAnswer4: "Yes, all medical weight loss medications require a prescription from a licensed healthcare provider after a thorough medical evaluation.",
    faqQuestion5: "Do you offer in-person consultations?",
    faqAnswer5: "Yes, we offer both in-person consultations at our clinic locations and convenient telehealth options.",
    faqQuestion6: "How do I get started?",
    faqAnswer6: "Getting started is easy! Simply book an intake session online or contact our office to schedule your initial evaluation.",
};
