services:
    app:
        image: softvence/${PACKAGE_NAME}:latest
        container_name: ${PACKAGE_NAME}
        profiles:
            - prod
        platform: linux/amd64
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5056:5056
        env_file:
            - .env.development
        depends_on:
            db:
                condition: service_healthy
        restart: unless-stopped
        networks:
            - doc
    db:
        image: postgres:16-alpine
        container_name: pg-db
        profiles:
            - dev
            - prod
        environment:
            - POSTGRES_USER=doc
            - POSTGRES_PASSWORD=doc
            - POSTGRES_DB=doc
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 5432:5432
        volumes:
            - doc_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U doc -d doc"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped
        networks:
            - doc

volumes:
    doc_data:
        driver: local
networks:
    doc:
        driver: bridge
