// Provider License seed data matching the Compliance Center screenshot
// Doctor cards: Dr. Sarah Mitchell (TX, CA, FL), Dr. James Okafor (TX, NY),
//               Emily Torres NP (TX), Dr. Kevin Nash (CA, WA)
export const DEFAULT_PROVIDER_LICENSES = [
    {
        doctorName: "Dr. Sarah Mitchell",
        doctorEmail: "s.mitchell@weightlossmd.com",
        avatarColor: "#1e3a5f",
        npiNumber: "1234567890",
        deaNumber: "BM1234567",
        licenseNumber: "LIC-SM-TX-001",
        licenseType: "MD",
        licenseStates: ["TX", "CA", "FL"],
        licenseSource: "PRIMARY" as const,
        licenseStatus: "EXPIRING_SOON" as const,
        licenseExpiresAt: new Date(Date.now() + 72 * 24 * 60 * 60 * 1000), // 72 days
        insuranceProvider: "BlueCross BlueShield",
        insuranceStatus: "EXPIRING_SOON" as const,
        insuranceExpiresAt: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000), // 27 days
        isActive: true,
    },
    {
        doctorName: "Dr. James Okafor",
        doctorEmail: "j.okafor@weightlossmd.com",
        avatarColor: "#1a4a3a",
        npiNumber: "0987654321",
        deaNumber: "BO9876543",
        licenseNumber: "LIC-JO-TX-002",
        licenseType: "MD",
        licenseStates: ["TX", "NY"],
        licenseSource: "PRIMARY" as const,
        licenseStatus: "EXPIRING_SOON" as const,
        licenseExpiresAt: new Date(Date.now() + 118 * 24 * 60 * 60 * 1000), // 118 days
        insuranceProvider: "Aetna",
        insuranceStatus: "ACTIVE" as const,
        insuranceExpiresAt: new Date(Date.now() + 225 * 24 * 60 * 60 * 1000), // 225 days
        isActive: true,
    },
    {
        doctorName: "Emily Torres NP",
        doctorEmail: "e.torres@weightlossmd.com",
        avatarColor: "#3a1a1a",
        npiNumber: "1122334455",
        deaNumber: null,
        licenseNumber: "LIC-ET-TX-003",
        licenseType: "NP",
        licenseStates: ["TX"],
        licenseSource: "PRIMARY" as const,
        licenseStatus: "ACTIVE" as const,
        licenseExpiresAt: new Date(Date.now() + 400 * 24 * 60 * 60 * 1000),
        insuranceProvider: "United Healthcare",
        insuranceStatus: "EXPIRING_SOON" as const,
        insuranceExpiresAt: new Date(Date.now() + 36 * 24 * 60 * 60 * 1000), // 36 days
        isActive: true,
    },
    {
        doctorName: "Dr. Kevin Nash",
        doctorEmail: "k.nash@weightlossmd.com",
        avatarColor: "#1a1a3a",
        npiNumber: "5544332211",
        deaNumber: "BN5544332",
        licenseNumber: "LIC-KN-CA-004",
        licenseType: "MD",
        licenseStates: ["CA", "WA"],
        licenseSource: "PRIMARY" as const,
        licenseStatus: "ACTIVE" as const,
        licenseExpiresAt: new Date(Date.now() + 270 * 24 * 60 * 60 * 1000), // 270 days
        insuranceProvider: "Cigna",
        insuranceStatus: "ACTIVE" as const,
        insuranceExpiresAt: new Date(Date.now() + 270 * 24 * 60 * 60 * 1000), // 270 days
        isActive: true,
    },
    // Additional providers for realistic totals
    {
        doctorName: "Dr. Rachel Green",
        doctorEmail: "r.green@weightlossmd.com",
        npiNumber: "6677889900",
        licenseType: "MD",
        licenseStates: ["TX", "OK"],
        licenseSource: "PRIMARY" as const,
        licenseStatus: "ACTIVE" as const,
        licenseExpiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        insuranceStatus: "ACTIVE" as const,
        insuranceExpiresAt: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isActive: true,
    },
    {
        doctorName: "Dr. Patrick Hughes",
        doctorEmail: "p.hughes@weightlossmd.com",
        npiNumber: "7788990011",
        licenseType: "DO",
        licenseStates: ["FL", "GA"],
        licenseSource: "PRIMARY" as const,
        licenseStatus: "EXPIRING_SOON" as const,
        licenseExpiresAt: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        insuranceStatus: "ACTIVE" as const,
        insuranceExpiresAt: new Date(Date.now() + 200 * 24 * 60 * 60 * 1000),
        isActive: true,
    },
    {
        doctorName: "Dr. Sofia Morales",
        doctorEmail: "s.morales@weightlossmd.com",
        npiNumber: "8899001122",
        licenseType: "MD",
        licenseStates: ["CA", "NV"],
        licenseSource: "PRIMARY" as const,
        licenseStatus: "EXPIRED" as const,
        licenseExpiresAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        insuranceStatus: "EXPIRED" as const,
        insuranceExpiresAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        isActive: true,
    },
    {
        doctorName: "James Parker PA",
        doctorEmail: "j.parker@weightlossmd.com",
        npiNumber: "9900112233",
        licenseType: "PA",
        licenseStates: ["TX"],
        licenseSource: "PRIMARY" as const,
        licenseStatus: "PENDING" as const,
        insuranceStatus: "PENDING" as const,
        isActive: true,
    },
];
