// Incident seed data matching the screenshot (7 incidents)
export const DEFAULT_INCIDENTS = [
    {
        incidentId: "INC-001",
        type: "Unauthorized Access Attempt",
        severity: "CRITICAL" as const,
        status: "OPEN" as const,
        source: "SECURITY_SCAN" as const,
        affectedSystem: "Authentication Service",
        reportedBy: "Unknown (IP: 45.33.32.156)",
        assignedTo: "Dr. Admin",
        description: "3 failed login attempts from unrecognized device",
        detectedAt: new Date("2026-06-04T09:14:32Z"),
        isActive: true,
    },
    {
        incidentId: "INC-002",
        type: "Suspicious Login",
        severity: "HIGH" as const,
        status: "INVESTIGATING" as const,
        source: "SYSTEM_MONITORING" as const,
        affectedSystem: "Patient Portal",
        reportedBy: "Dr. Michael Chen",
        assignedTo: "Sarah K",
        description: "Login from new location: Dallas, TX (usual: Boston, MA)",
        detectedAt: new Date("2026-06-04T08:45:00Z"),
        isActive: true,
    },
    {
        incidentId: "INC-003",
        type: "PHI Export Event",
        severity: "HIGH" as const,
        status: "INVESTIGATING" as const,
        source: "SYSTEM_MONITORING" as const,
        affectedSystem: "Export Module",
        reportedBy: "Jessica Martinez",
        assignedTo: "Thomas R",
        description: "Large PHI export detected — exceeds daily threshold",
        detectedAt: new Date("2026-06-04T07:30:00Z"),
        isActive: true,
    },
    {
        incidentId: "INC-004",
        type: "Bulk Data Download",
        severity: "MEDIUM" as const,
        status: "RESOLVED" as const,
        source: "SYSTEM_MONITORING" as const,
        affectedSystem: "Billing System",
        reportedBy: "Billing Staff #7",
        assignedTo: "Admin",
        description: "Bulk patient record download detected",
        detectedAt: new Date("2026-06-03T15:22:11Z"),
        resolvedAt: new Date("2026-06-03T17:00:00Z"),
        isActive: true,
    },
    {
        incidentId: "INC-005",
        type: "Multiple Failed Logins",
        severity: "MEDIUM" as const,
        status: "RESOLVED" as const,
        source: "SECURITY_SCAN" as const,
        affectedSystem: "Authentication Service",
        reportedBy: "David Wilson",
        assignedTo: "Support",
        description: "5 failed login attempts — account temporarily locked",
        detectedAt: new Date("2026-06-03T14:00:00Z"),
        resolvedAt: new Date("2026-06-03T15:30:00Z"),
        isActive: true,
    },
    {
        incidentId: "INC-006",
        type: "Unauthorized Access Attempt",
        severity: "CRITICAL" as const,
        status: "OPEN" as const,
        source: "SECURITY_SCAN" as const,
        affectedSystem: "Admin Panel",
        reportedBy: "Unknown (IP: 10.0.0.45)",
        assignedTo: "Support",
        description: "Multiple access attempts to restricted admin endpoint",
        detectedAt: new Date("2026-06-02T22:15:00Z"),
        isActive: true,
    },
    {
        incidentId: "INC-007",
        type: "Suspicious Login",
        severity: "LOW" as const,
        status: "RESOLVED" as const,
        source: "USER_REPORT" as const,
        affectedSystem: "Patient Portal",
        reportedBy: "Emily Chen",
        assignedTo: "Support",
        description: "Patient reported unrecognized login to their account",
        detectedAt: new Date("2026-06-02T11:05:00Z"),
        resolvedAt: new Date("2026-06-02T12:00:00Z"),
        isActive: true,
    },
    // Additional incidents for realistic totals
    ...Array.from({ length: 118 }, (_, i) => ({
        incidentId: `INC-${String(i + 8).padStart(3, "0")}`,
        type: ["PHI Access Anomaly", "Data Export", "Failed Login", "Unauthorized Access"][i % 4],
        severity: (["CRITICAL", "HIGH", "MEDIUM", "LOW"] as const)[i % 4],
        status: (["RESOLVED", "CLOSED", "RESOLVED", "CLOSED"] as const)[i % 4],
        source: (["SECURITY_SCAN", "SYSTEM_MONITORING", "USER_REPORT", "MANUAL"] as const)[i % 4],
        reportedBy: ["System", "Admin", "Security Team", "User Report"][i % 4],
        assignedTo: ["Admin", "Support", "Security", "Compliance"][i % 4],
        description: `Historical incident #${i + 8} — auto-resolved.`,
        detectedAt: new Date(Date.now() - (i + 8) * 24 * 60 * 60 * 1000),
        resolvedAt: new Date(Date.now() - (i + 7) * 24 * 60 * 60 * 1000),
        isActive: true,
    })),
];
